name: build


on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: ['1.21']
    name: Build
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v3.11.0
        with:
          java-version: '18'
          distribution: 'temurin'
      - name: Clone project
        run: |
          rm -rf project
          rm -rf jar/xiaoya_proxy.jar
          git clone --recurse-submodules https://github.com/zengge99/XiaoyaVod project
      - name: Download baksmali
        working-directory: ./project
        run: |
          mkdir -p jar/3rd
          wget https://bitbucket.org/JesusFreke/smali/downloads/baksmali-2.5.2.jar -O jar/3rd/baksmali-2.5.2.jar
      - name: Customize Spider
        working-directory: ./project
        run: |
          sed -i 's/gradle-7.4.2-all/gradle-7.5-bin/g' gradle/wrapper/gradle-wrapper.properties
          #sed -i 's/原畫/原画/g;s/普畫/普画/g;s/轉存/转存/g;s/極速/极速/g' app/src/main/java/com/github/catvod/spider/Ali.java
          #sed -i 's/原畫/原画/g;s/普畫/普画/g;s/轉存/转存/g;s/極速/极速/g;s/阿里雲盤/阿里云盘/g' app/src/main/java/com/github/catvod/api/AliYun.java
          #curl -L https://github.com/oiltea/CatVodSpider/raw/9ab5cc627be4096db11bca9ee9177c13014ddadd/app/src/main/java/com/github/catvod/spider/Wogg.java > app/src/main/java/com/github/catvod/spider/Wogg.java
          #sed -i 's/thread = 10/thread = 64/g' app/src/main/java/com/github/catvod/api/AliYun.java
      - name: Build the app
        working-directory: ./project
        run: |
          chmod +x gradlew
          ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all
      - name: Customize Spider Jar
        working-directory: ./project
        run: |
          rm -rf jar/xiaoya_proxy.jar
          rm -rf jar/spider.jar/original/META-INF
          curl -L https://github.com/iBotPeaches/Apktool/releases/download/v2.7.0/apktool_2.7.0.jar > jar/3rd/apktool_2.7.0.jar
          java -jar jar/3rd/baksmali-2.5.2.jar d app/build/intermediates/dex/release/minifyReleaseWithR8/classes.dex -o jar/Smali_classes
          mkdir -p jar/spider.jar/smali/com/github/catvod/
          mv jar/Smali_classes/com/github/catvod/spider jar/spider.jar/smali/com/github/catvod/
          java -jar jar/3rd/apktool_2.7.0.jar b jar/spider.jar -c
          mv jar/spider.jar/dist/dex.jar ../jar/xiaoya_proxy.jar
          md5=($(md5sum ../jar/xiaoya_proxy.jar))
          echo $md5 > ../jar/xiaoya_proxy.jar.md5
      - name: Upload APK
        uses: actions/upload-pages-artifact@v3
        with:
          name: Spider
          path: ./jar/
      - name: Update spider jar
        uses: EndBug/add-and-commit@v9.1.3
        with:
          default_author: github_actions
          message: 'update spider jar'
          add: "['./jar/xiaoya_proxy.jar', './jar/xiaoya_proxy.jar.md5']"
